export const ADD_SOFT_SKILL_REQUIRE = "ADD_SOFT_SKILL_REQUIRE"
export const ADD_HARD_SKILL_REQUIRE = "ADD_HARD_SKILL_REQUIRE"
export const DELETE_SOFT_SKILL_REQUIRE = "DELETE_SOFT_SKILL_REQUIRE"
export const DELETE_HARD_SKILL_REQUIRE = "DELETE_HARD_SKILL_REQUIRE"