export const ADD_POSITION_REQUIRE = "ADD_POSITION_REQUIRE"
export const DELETE_POSITION_REQUIRE = "DELETE_POSITION_REQUIRE"
export const UPDATE_POSITION_ID = "UPDATE_POSITION_ID"
export const UPDATE_POSITION_NOC = "UPDATE_POSITION_NOC"

export const ADD_LANGUAGE_REQUIRE = "ADD_LANGUAGE_REQUIRE"
export const DELETE_LANGUAGE_REQUIRE = "DELETE_LANGUAGE_REQUIRE"
export const UPDATE_LANGUAGE = "UPDATE_LANGUAGE"

export const ADD_SOFT_SKILL_REQUIRE = "ADD_SOFT_SKILL_REQUIRE"
export const DELETE_SOFT_SKILL_REQUIRE = "DELETE_SOFT_SKILL_REQUIRE"
export const UPDATE_SOFT_SKILL = "UPDATE_SOFT_SKILL"

export const ADD_HARD_SKILL_REQUIRE = "ADD_HARD_SKILL_REQUIRE"
export const DELETE_HARD_SKILL_REQUIRE = "DELETE_HARD_SKILL_REQUIRE"
export const UPDATE_HARD_SKILL_EXP_PRIORITY = "UPDATE_HARD_SKILL_EXP_PRIORITY"
export const UPDATE_HARD_SKILL_ID = "UPDATE_HARD_SKILL_ID"
export const UPDATE_HARD_SKILL_CERTI = "UPDATE_HARD_SKILL_CERTI"


export const FETCH_POSITION_LIST = "FETCH_POSITION_LIST"
export const FETCH_SOFT_SKILL_LIST = "FETCH_SOFT_SKILL_LIST"
export const FETCH_HARD_SKILL_LIST = "FETCH_HARD_SKILL_LIST"
export const FETCH_CERTIFICATION_LIST = "FETCH_CERTIFICATION_LIST"

export const GENERATE_PROJECT = "GENERATE_PROJECT"
export const CREATE_PROJECT = "CREATE_PROJECT"
export const UPDATE_PROJECT_DETAIL = "UPDATE_PROJECT_DETAIL"
export const UPDATE_PROJECT = "UPDATE_PROJECT"
export const FETCH_PROJECT = "FETCH_PROJECT"
export const FETCH_PROJECT_DETAIL = "FETCH_PROJECT_DETAIL"

export const CREATE_POSITION = "CREATE_POSITION"